parameters:
- name: environmentName
  type: string
  default: 'dev'

variables:
  - group: networking-vars

stages:
  - stage: Prerequisites
    displayName: 'Prerequisites'
    jobs:
    - job: Prerequisites
      displayName: 'Prerequisites'
      steps:
      - checkout: self
      - template: templates/prerequisites.yml
  
  - stage: Integration
    dependsOn: Prerequisites
    displayName: 'CI'
    jobs:
    - job: CI
      displayName: 'Integration'
      steps:
      - checkout: self
      - template: templates/integration.yml

  - stage: Validation
    displayName: 'Validation'
    dependsOn: Integration
    jobs:
    - job: Planning
      displayName: 'Terraform Plan'
      steps:
      - template: templates/validation.yml

  - stage: Deploy
    displayName: 'CD'
    dependsOn: Approval
    condition: succeeded()
    jobs:
    - job: Applying
      displayName: 'Terraform Apply'
      steps:
      - template: templates/deploy.yml
