jobs:
# Notificación antes de la aprobación
  - job: NotifyApproval
    displayName: "Enviar Notificación Interactiva a Google Chat"
    pool: Azure Pipelines
    steps:
      - script: |
          PIPELINE_URL="$(System.CollectionUri)$(System.TeamProject)/_build/results?buildId=$(Build.BuildId)&view=results"
          APPROVERS = "$(CLOUDOPSAPPROVERS)"

          curl -X POST -H "Content-Type: application/json" \
          -d '{
            "cards": [
                {
                    "header": {
                        "title": "🚀 Aprobación requerida en Azure DevOps",
                        "subtitle": "Pipeline: '"$(Build.DefinitionName)"' - Run: '"$(Build.BuildNumber)"'"
                    },
                    "sections": [
                        {
                            "widgets": [
                                {
                                    "textParagraph": {
                                        "text": "👤 *Solicitado por:* '"$(Build.RequestedFor)"'\n✅ *Aprobación requerida de:* '"$(CLOUDOPSAPPROVERS)"'"
                                    }
                                },
                                {
                                    "buttons": [
                                        {
                                            "textButton": {
                                                "text": "Review Approval",
                                                "onClick": {
                                                    "openLink": {
                                                        "url": "'"$PIPELINE_URL"'"
                                                    }
                                                }
                                            }
                                        }
                                    ]
                                }
                            ]
                        }
                    ]
                }
            ]
          }' \
          "https://chat.googleapis.com/v1/spaces/AAAAURmqa_s/messages?key=AIzaSyDdI0hCZtE6vySjMm-WEfRq3CPzqKqqsHI&token=ELpWoDZbTn-EosCsgMUdDCUR4TZhp2kv1hx_Qu2fgBo"
        displayName: "Enviar Notificación Interactiva a Google Chat - CloudOps"

# Aprobación manual en un job sin agente (pool: server)
  - job: Approval
    displayName: "Awaiting manual approval"
    dependsOn: NotifyApproval
    pool: server
    timeoutInMinutes: 720
    steps:
      - task: ManualValidation@0
        timeoutInMinutes: 360
        name: cloudOpsApproval
        inputs:
          notifyUsers: |
            $(CLOUDOPSAPPROVERS)
          instructions: 'Please review the Terraform plan before applying changes. You can continue or reject the deployment.'
          onTimeout: 'reject'
        displayName: "Approval CloudOps"
      
      - task: ManualValidation@0
        timeoutInMinutes: 360
        name: architectureApproval
        inputs:
          notifyUsers: |
            $(ARCHITECTUREAPPROVERS)
          instructions: 'Please review the Terraform plan before applying changes. You can continue or reject the deployment.'
          onTimeout: 'reject'
        displayName: "Approval Architecture"
